### ISSUE TITLE
weather forecast broken with HA Release 2024.4.3 

### ISSUE THREAD

**Issue by fhb** [kotope/esphome_eink_dashboard#3]
The weather forecast attribute has been removed with Release 2024.4.3 - April 12, any plans on updating the yaml? Otherwise I'll try to recreate it with the current implementation.

"The previously deprecated forecast attribute of weather entities, has now been removed. Use the [weather.get_forecasts](https://www.home-assistant.io/integrations/weather#service-weatherget_forecasts) service to get the forecast data instead."

Edit:
you don't have to change anything. I just added the following code to my configuration.yaml
```
template:
  - trigger:
    - platform: state
      entity_id: weather.forecast_home
    - platform: homeassistant
      event: start
    - platform: event
      event_type: event_template_reloaded
    action:
      - service: weather.get_forecasts
        data:
          type: daily
        target:
          entity_id: weather.forecast_home
        response_variable: daily
    sensor:
      - name: Weather metno Daily Forecast
        unique_id: weather_forecast_metno_daily
        state: "{{ states('weather.forecast_home') }}"
        attributes:
          forecast: "{{ daily['weather.forecast_home'].forecast }}"
```

and changed part of the esphome yml to 
```
- platform: homeassistant
    entity_id: sensor.weather_metno_daily_forecast
    attribute: forecast
    id: w_forecast
    internal: true
```
